openapi: 3.0.3

info:
  title: DAPE
  description: DAPE API contract - Declaração de Apostas Esportivas
  contact:
    email: efchaves@uolinc.com
  version: 1.0.0

servers:
  - url: http://localhost:8080/dape
    description: Servidor local

tags:
  - name: bet
    description: Operações relacionadas a apostas
  - name: ticket
    description: Operações relacionadas a bilhetes de apostas

paths:
  /bet:
    post:
      tags:
        - bet
      summary: Cadastrar aposta
      description: Realizar o cadastro de uma nova aposta na base de dados
      operationId: cadastrarAposta
      requestBody:
        description: Cadastro de uma nova aposta no banco de dados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BetCreateRequest'
        required: true
      responses:
        '201':
          description: Created, Aposta cadastrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BetCreateResponse'
        '400':
          description: Bad Request, Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - bet
      summary: Consultar apostas
      description: Consultar as apostas disponíveis no banco de dados
      operationId: consultarAposta
      parameters:
        - name: page
          in: query
          required: false
          explode: true
          schema:
            type: integer
            format: int32
            example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            example: 5
        - name: bet_status
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/StatusEnum'
        - name: dat_created
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2025-07-21"
        - name: dat_updated
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2025-08-07"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BetListResponse'
        '400':
          description: Bad Request, Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /bet/{idt_bet}/status:
    patch:
      tags:
        - bet
      summary: Atualizar status
      description: Realizar atualização do status da aposta
      operationId: atualizarStatusAposta
      parameters:
        - name: idt_bet
          in: path
          required: true
          explode: true
          schema:
            type: string
            example: "1"
      requestBody:
        description: Atualização do status de uma aposta no banco de dados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusUpdateRequest'
        required: true
      responses:
        '200':
          description: OK, Status Atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusUpdateResponse'
        '400':
          description: Bad Request, Status inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found, Aposta não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /bet/{idt_bet}:
    patch:
      tags:
        - bet
      summary: Atualizar aposta
      description: Realizar atualização de aposta disponível na base de dados
      operationId: atualizarAposta
      parameters:
        - name: idt_bet
          in: path
          required: true
          explode: true
          schema:
            type: string
            example: "1"
      requestBody:
        description: Atualização de uma aposta no banco de dados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BetUpdateRequest'
        required: true
      responses:
        '200':
          description: OK, Aposta Atualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BetUpdateResponse'
        '400':
          description: Bad Request, Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found, Aposta não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - bet
      summary: Deletar aposta
      description: Deletar uma aposta disponível no banco de dados
      operationId: deletarAposta
      parameters:
        - name: idt_bet
          in: path
          required: true
          explode: true
          schema:
            type: string
            example: "1"
      responses:
        '200':
          description: OK, Aposta Deletada
        '404':
          description: Not found, Aposta não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ticket:
    post:
      tags:
        - ticket
      summary: Registrar bilhete
      description: Realizar o registro de um bilhete de apostas
      operationId: registrarAposta
      requestBody:
        description: Registro de um novo bilhete de apostas
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketCreateRequest'
        required: true
      responses:
        '201':
          description: Created, Bilhete registrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketCreateResponse'
        '400':
          description: Bad Request, Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags:
        - ticket
      summary: Consultar bilhetes
      description: Consultar os bilhetes com as apostas realizadas
      operationId: consultarBilhete
      parameters:
        - name: page
          in: query
          required: false
          explode: true
          schema:
            type: integer
            format: int32
            example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            example: 5
        - name: ticket_status
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/StatusEnum'
        - name: ticket_type
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/TicketTypeEnum'
        - name: idt_client
          in: query
          required: false
          schema:
            type: integer
            format: int32
            example: 7
        - name: dat_created
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2025-07-21"
        - name: dat_updated
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2025-08-07"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketListResponse'
        '400':
          description: Bad Request, Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    BetCreateRequest:
      required:
        - num_odd
        - des_bet
      type: object
      properties:
        num_odd:
          type: number
          format: double
          example: 2.19
        des_bet:
          type: string
          example: "Vitória do Botafogo"
      xml:
        name: BetCreateRequest

    BetCreateResponse:
      type: object
      properties:
        bet_status:
          $ref: '#/components/schemas/StatusEnum'
        idt_bet:
          type: integer
          format: int32
          example: 2
        num_odd:
          type: number
          format: double
          example: 2.19
        des_bet:
          type: string
          example: "Vitória do Botafogo"
        dat_created:
          type: string
          format: date
          example: "2025-07-21"
      xml:
        name: BetCreateRequest

    BetUpdateRequest:
      required:
        - num_odd
        - des_bet
      properties:
        num_odd:
          type: number
          format: double
          example: 1.90
        des_bet:
          type: string
          example: "Vitória do Botafogo"
      xml:
        name: BetUpdateRequest

    BetUpdateResponse:
      properties:
        num_odd:
          type: number
          format: double
          example: 1.90
        des_bet:
          type: string
          example: "Vitória do Botafogo"
        dat_created:
          type: string
          format: date
          example: "2025-07-21"
        dat_updated:
          type: string
          format: date
          example: "2025-08-06"
        bet_status:
          $ref: '#/components/schemas/StatusEnum'
      xml:
        name: BetUpdateResponse

    StatusUpdateRequest:
      type: object
      properties:
        bet_status:
          $ref: '#/components/schemas/StatusEnum'
      xml:
        name: StatusUpdateRequest

    StatusUpdateResponse:
      properties:
        num_odd:
          type: number
          format: double
          example: 1.90
        des_bet:
          type: string
          example: "Vitória do Botafogo"
        bet_status:
          $ref: '#/components/schemas/StatusEnum'
        dat_created:
          type: string
          format: date
          example: "2025-07-21"
        dat_updated:
          type: string
          format: date
          example: "2025-08-06"
      xml:
        name: StatusUpdateResponse

    BetListResponse:
      type: object
      properties:
        size:
          type: integer
          format: int32
          example: 10
        total_size:
          type: integer
          format: int32
          example: 1000
        page:
          type: integer
          format: int32
          example: 0
          default: 0
        total_pages:
          type: integer
          format: int32
          example: 100
        content:
          type: array
          items:
            type: object
            properties:
              num_odd:
                type: number
                format: double
                example: 2.19
              des_bet:
                type: string
                example: "Vitória do Botafogo"
              bet_status:
                $ref: '#/components/schemas/StatusEnum'
              dat_created:
                type: string
                format: date
                example: "2025-07-21"
              dat_updated:
                type: string
                format: date
                example: "2025-08-06"
      xml:
        name: BetListResponse

    TicketCreateRequest:
      required:
        - num_amount
        - idt_client
        - idt_bet
      type: object
      properties:
        num_amount:
          type: integer
          format: double
          example: 100.01
        idt_client:
          type: integer
          format: int32
          example: 8
        idt_bet:
          type: array
          items:
            type: integer
            format: int32
          example: [1, 4, 6]
      xml:
        name: TicketCreateRequest

    TicketCreateResponse:
      type: object
      properties:
        ticket_status:
          $ref: '#/components/schemas/StatusEnum'
        idt_ticket:
          type: integer
          format: int32
          example: 2
        num_amount:
          type: integer
          format: double
          example: 100.01
        ticket_type:
          $ref: '#/components/schemas/TicketTypeEnum'
        num_final_odd:
          type: integer
          format: double
          example: 5.76
        dat_created:
          type: string
          format: date
          example: "2025-07-21"
        client:
          type: object
          properties:
            idt_client:
              type: integer
              format: int32
              example: 7
            nam_client:
              type: string
              example: "Ted Lasso"
            num_document:
              type: string
              example: "123.456.789-00"
            num_balance:
              type: integer
              format: double
              example: 200.00
      xml:
        name: TicketCreateResponse

    TicketListResponse:
      type: object
      properties:
        size:
          type: integer
          format: int32
          example: 10
        total_size:
          type: integer
          format: int32
          example: 1000
        page:
          type: integer
          format: int32
          example: 0
          default: 0
        total_pages:
          type: integer
          format: int32
          example: 100
        content:
          type: array
          items:
            type: object
            properties:
              num_amount:
                type: integer
                format: double
                example: 100.01
              dat_created:
                type: string
                format: date
                example: "2025-07-21"
              ticket_type:
                $ref: '#/components/schemas/TicketTypeEnum'
              num_final_odd:
                type: integer
                format: double
                example: 5.76
              ticket_status:
                $ref: '#/components/schemas/StatusEnum'
              client:
                type: object
                properties:
                  idt_client:
                    type: integer
                    format: int32
                    example: 7
                  nam_client:
                    type: string
                    example: "Ted Lasso"
                  num_document:
                    type: string
                    example: "123.456.789-00"
                  num_balance:
                    type: integer
                    format: double
                    example: 200.00
      xml:
        name: TicketListResponse

    StatusEnum:
      type: string
      enum:
        - PENDING
        - GREEN
        - RED
      xml:
        name: StatusEnum

    TicketTypeEnum:
      type: string
      enum:
        - MULTIPLE
        - SIMPLE
      xml:
        name: TicketTypeEnum

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: "Mensagem de erro"
      xml:
        name: ErrorResponse


