CREATE TABLE BET_STATUS (
    COD_BET_STATUS NUMBER(3) PRIMARY KEY NOT NULL,
    DES_BET_STATUS VARCHAR2(25) NOT NULL
);

CREATE TABLE TICKET_STATUS (
  COD_TICKET_STATUS NUMBER(3) PRIMARY KEY NOT NULL,
  DES_TICKET_STATUS VARCHAR2(25) NOT NULL
);

CREATE TABLE TICKET_TYPE (
  COD_TICKET_TYPE NUMBER(3) PRIMARY KEY NOT NULL,
  DES_TICKET_TYPE VARCHAR2(25) NOT NULL
);

CREATE TABLE BET (
    IDT_BET NUMBER(20) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NUM_ODD NUMBER(10, 2) NOT NULL,
    FLG_SELECTED NUMBER(1) NOT NULL,
    DAT_CREATED TIMESTAMP NOT NULL,
    DAT_UPDATED TIMESTAMP NOT NULL,
    DES_BET VARCHAR2(200) NOT NULL,
    COD_BET_STATUS NUMBER(3) NOT NULL,
    CONSTRAINT COD_BET_STATUS FOREIGN KEY (COD_BET_STATUS) REFERENCES BET_STATUS (COD_BET_STATUS)
);

CREATE TABLE CLIENT (
    IDT_CLIENT NUMBER(20) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    NAM_CLIENT VARCHAR2(50) NOT NULL,
    NUM_DOCUMENT VARCHAR2(14) NOT NULL,
    NUM_BALANCE NUMBER(10, 2) NOT NULL,
    DES_EMAIL VARCHAR2(50) NOT NULL,
    NUM_PASSWORD VARCHAR2(68) NOT NULL,
    DAT_CREATED TIMESTAMP NOT NULL,
    DAT_UPDATED TIMESTAMP NOT NULL
);

CREATE TABLE TICKET (
    IDT_TICKET NUMBER(20) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    NUM_AMOUNT NUMBER(10, 2) NOT NULL,
    DAT_CREATED TIMESTAMP NOT NULL,
    DAT_UPDATED TIMESTAMP NOT NULL,
    COD_TICKET_TYPE NUMBER(3) NOT NULL,
    COD_TICKET_STATUS NUMBER(3) NOT NULL,
    IDT_CLIENT NUMBER(20) NOT NULL,
    CONSTRAINT COD_TICKET_TYPE FOREIGN KEY (COD_TICKET_TYPE) REFERENCES TICKET_TYPE (COD_TICKET_TYPE),
    CONSTRAINT COD_TICKET_STATUS FOREIGN KEY (COD_TICKET_STATUS) REFERENCES TICKET_STATUS (COD_TICKET_STATUS),
    CONSTRAINT IDT_CLIENT FOREIGN KEY (IDT_CLIENT) REFERENCES CLIENT (IDT_CLIENT)
);

CREATE TABLE TICKET_BET (
    IDT_TICKET_BET NUMBER(20) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    IDT_TICKET NUMBER(20) NOT NULL,
    IDT_BET NUMBER(20) NOT NULL,
    CONSTRAINT IDT_TICKET FOREIGN KEY (IDT_TICKET) REFERENCES TICKET (IDT_TICKET),
    CONSTRAINT IDT_BET FOREIGN KEY (IDT_BET) REFERENCES BET (IDT_BET)
);