/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dape.api.adapter.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Arquivo para atualização de bilhetes de apostas */
@org.apache.avro.specific.AvroGenerated
public class UpdateBetEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7129533813285178416L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UpdateBetEvent\",\"namespace\":\"com.dape.api.adapter.dto\",\"doc\":\"Arquivo para atualização de bilhetes de apostas\",\"fields\":[{\"name\":\"idt_bet\",\"type\":\"long\",\"doc\":\"[PK] ID gerado para cada aposta cadastrada\"},{\"name\":\"bet_status\",\"type\":\"int\",\"doc\":\"Status da aposta atualizada\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UpdateBetEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UpdateBetEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UpdateBetEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UpdateBetEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UpdateBetEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UpdateBetEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UpdateBetEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UpdateBetEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UpdateBetEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** [PK] ID gerado para cada aposta cadastrada */
  private long idt_bet;
  /** Status da aposta atualizada */
  private int bet_status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UpdateBetEvent() {}

  /**
   * All-args constructor.
   * @param idt_bet [PK] ID gerado para cada aposta cadastrada
   * @param bet_status Status da aposta atualizada
   */
  public UpdateBetEvent(java.lang.Long idt_bet, java.lang.Integer bet_status) {
    this.idt_bet = idt_bet;
    this.bet_status = bet_status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idt_bet;
    case 1: return bet_status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idt_bet = (java.lang.Long)value$; break;
    case 1: bet_status = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idt_bet' field.
   * @return [PK] ID gerado para cada aposta cadastrada
   */
  public long getIdtBet() {
    return idt_bet;
  }


  /**
   * Sets the value of the 'idt_bet' field.
   * [PK] ID gerado para cada aposta cadastrada
   * @param value the value to set.
   */
  public void setIdtBet(long value) {
    this.idt_bet = value;
  }

  /**
   * Gets the value of the 'bet_status' field.
   * @return Status da aposta atualizada
   */
  public int getBetStatus() {
    return bet_status;
  }


  /**
   * Sets the value of the 'bet_status' field.
   * Status da aposta atualizada
   * @param value the value to set.
   */
  public void setBetStatus(int value) {
    this.bet_status = value;
  }

  /**
   * Creates a new UpdateBetEvent RecordBuilder.
   * @return A new UpdateBetEvent RecordBuilder
   */
  public static com.dape.api.adapter.dto.UpdateBetEvent.Builder newBuilder() {
    return new com.dape.api.adapter.dto.UpdateBetEvent.Builder();
  }

  /**
   * Creates a new UpdateBetEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UpdateBetEvent RecordBuilder
   */
  public static com.dape.api.adapter.dto.UpdateBetEvent.Builder newBuilder(com.dape.api.adapter.dto.UpdateBetEvent.Builder other) {
    if (other == null) {
      return new com.dape.api.adapter.dto.UpdateBetEvent.Builder();
    } else {
      return new com.dape.api.adapter.dto.UpdateBetEvent.Builder(other);
    }
  }

  /**
   * Creates a new UpdateBetEvent RecordBuilder by copying an existing UpdateBetEvent instance.
   * @param other The existing instance to copy.
   * @return A new UpdateBetEvent RecordBuilder
   */
  public static com.dape.api.adapter.dto.UpdateBetEvent.Builder newBuilder(com.dape.api.adapter.dto.UpdateBetEvent other) {
    if (other == null) {
      return new com.dape.api.adapter.dto.UpdateBetEvent.Builder();
    } else {
      return new com.dape.api.adapter.dto.UpdateBetEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for UpdateBetEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UpdateBetEvent>
    implements org.apache.avro.data.RecordBuilder<UpdateBetEvent> {

    /** [PK] ID gerado para cada aposta cadastrada */
    private long idt_bet;
    /** Status da aposta atualizada */
    private int bet_status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.dape.api.adapter.dto.UpdateBetEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idt_bet)) {
        this.idt_bet = data().deepCopy(fields()[0].schema(), other.idt_bet);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bet_status)) {
        this.bet_status = data().deepCopy(fields()[1].schema(), other.bet_status);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing UpdateBetEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.dape.api.adapter.dto.UpdateBetEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.idt_bet)) {
        this.idt_bet = data().deepCopy(fields()[0].schema(), other.idt_bet);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bet_status)) {
        this.bet_status = data().deepCopy(fields()[1].schema(), other.bet_status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'idt_bet' field.
      * [PK] ID gerado para cada aposta cadastrada
      * @return The value.
      */
    public long getIdtBet() {
      return idt_bet;
    }


    /**
      * Sets the value of the 'idt_bet' field.
      * [PK] ID gerado para cada aposta cadastrada
      * @param value The value of 'idt_bet'.
      * @return This builder.
      */
    public com.dape.api.adapter.dto.UpdateBetEvent.Builder setIdtBet(long value) {
      validate(fields()[0], value);
      this.idt_bet = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idt_bet' field has been set.
      * [PK] ID gerado para cada aposta cadastrada
      * @return True if the 'idt_bet' field has been set, false otherwise.
      */
    public boolean hasIdtBet() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idt_bet' field.
      * [PK] ID gerado para cada aposta cadastrada
      * @return This builder.
      */
    public com.dape.api.adapter.dto.UpdateBetEvent.Builder clearIdtBet() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bet_status' field.
      * Status da aposta atualizada
      * @return The value.
      */
    public int getBetStatus() {
      return bet_status;
    }


    /**
      * Sets the value of the 'bet_status' field.
      * Status da aposta atualizada
      * @param value The value of 'bet_status'.
      * @return This builder.
      */
    public com.dape.api.adapter.dto.UpdateBetEvent.Builder setBetStatus(int value) {
      validate(fields()[1], value);
      this.bet_status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bet_status' field has been set.
      * Status da aposta atualizada
      * @return True if the 'bet_status' field has been set, false otherwise.
      */
    public boolean hasBetStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bet_status' field.
      * Status da aposta atualizada
      * @return This builder.
      */
    public com.dape.api.adapter.dto.UpdateBetEvent.Builder clearBetStatus() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UpdateBetEvent build() {
      try {
        UpdateBetEvent record = new UpdateBetEvent();
        record.idt_bet = fieldSetFlags()[0] ? this.idt_bet : (java.lang.Long) defaultValue(fields()[0]);
        record.bet_status = fieldSetFlags()[1] ? this.bet_status : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UpdateBetEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<UpdateBetEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UpdateBetEvent>
    READER$ = (org.apache.avro.io.DatumReader<UpdateBetEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.idt_bet);

    out.writeInt(this.bet_status);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.idt_bet = in.readLong();

      this.bet_status = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.idt_bet = in.readLong();
          break;

        case 1:
          this.bet_status = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










